import type { HackathonDetailRead } from "../model/hackathonTypes";

export const mockHackathons: HackathonDetailRead[] = [
  {
    id: 2,
    title: "AI Challenge 2026",
    description:
      "Хакатон по искусственному интеллекту и машинному обучению. Работайте с реальными датасетами от компаний-партнеров, создавайте ML-модели и AI-решения для актуальных бизнес-задач.",
    status: "IN_PROGRESS",
    topics: ["AI", "LLM", "Computer Vision", "Python"],
    total_participants: 312,
    total_teams: 64,
    min_team_size: 1,
    max_team_size: 4,
    max_participants: 800,
    event_location: "Saint Petersburg",
    start_date: "2026-07-05T18:00:00",
    end_date: "2026-07-07T18:00:00",
    prizes: [
      { id: 1, title: "1-е место", reward: "500000" },
      { id: 2, title: "2-е место", reward: "200000" },
      { id: 3, title: "3-е место", reward: "100000" },
      { id: 4, title: "Лучший AI-продукт", reward: "100000" },
    ],
    submission_requirements: [
      "Команда от 1 до 4 человек",
      "Опыт в Machine Learning или Deep Learning",
      "Знание Python и основных ML-библиотек (TensorFlow, PyTorch, sklearn)",
      "Решение должно быть оформлено в виде Jupyter Notebook",
    ],
  },
  {
    id: 3,
    title: "BlockchainHack 2026",
    description:
      "Хакатон в области блокчейн технологий и децентрализованных приложений. Разрабатывайте смарт-контракты, DApps и DeFi-протоколы. Задачи от ведущих блокчейн-компаний и DeFi-протоколов.",
    status: "REGISTRATION",
    topics: ["AI", "Web3", "DeFi", "Rust"],
    total_participants: 200,
    total_teams: 48,
    min_team_size: 1,
    max_team_size: 4,
    max_participants: 1000,
    event_location: "Online",
    start_date: "2026-07-10T18:00:00",
    end_date: "2026-07-12T18:00:00",
    prizes: [
      { id: 1, title: "1-е место", reward: "200000" },
      { id: 2, title: "2-е место", reward: "100000" },
      { id: 3, title: "3-е место", reward: "50000" },
    ],
    submission_requirements: [
      "Команда от 1 до 4 человек",
      "Знание Solidity или Rust",
      "Понимание принципов блокчейна",
      "Развернутый смарт-контракт в тестовой сети",
    ],
  },
  {
    id: 4,
    title: "GameDev Jam 2025",
    description:
      "Хакатон по разработке игр. За 48 часов участники создали 118 оригинальных игровых прототипов в различных жанрах. Развивайте свои навыки геймдева и создавайте увлекательные игры.",
    status: "FINISHED",
    topics: ["C#", "Unreal", "Godot", "Go"],
    total_participants: 600,
    total_teams: 118,
    min_team_size: 1,
    max_team_size: 4,
    max_participants: 600,
    event_location: "Moscow",
    start_date: "2026-05-18T18:00:00",
    end_date: "2026-05-20T18:00:00",
    prizes: [
      { id: 1, title: "1-е место", reward: "150000" },
      { id: 2, title: "2-е место", reward: "70000" },
      { id: 3, title: "3-е место", reward: "30000" },
    ],
    submission_requirements: [
      "Команда от 1 до 4 человек",
      "Рабочий билд игры",
      "Исходный код проекта",
      "Краткое описание геймплея",
    ],
  },
  {
    id: 5,
    title: "FinTech 2025",
    description:
      "Хакатон финансовых технологий при поддержке крупнейших банков и платёжных систем России. Создавайте решения для финтеха: платежные системы, кредитные скоринги, fraud detection и другие актуальные задачи.",
    status: "FINISHED",
    topics: ["ML", "Python", "React", "Go"],
    total_participants: 847,
    total_teams: 142,
    min_team_size: 1,
    max_team_size: 4,
    max_participants: 1000,
    event_location: "Moscow",
    start_date: "2026-04-18T18:00:00",
    end_date: "2026-04-20T18:00:00",
    prizes: [
      { id: 1, title: "1-е место", reward: "400000" },
      { id: 2, title: "2-е место", reward: "150000" },
      { id: 3, title: "3-е место", reward: "50000" },
    ],
    submission_requirements: [
      "Команда от 1 до 4 человек",
      "Рабочий прототип приложения",
      "Презентация решения",
      "Исходный код на GitHub",
    ],
  },
  {
    id: 6,
    title: "CyberSecurity Cup",
    description:
      "Соревнования по кибербезопасности в формате CTF (Capture The Flag). Решайте задачи по веб-безопасности, криптографии, реверс-инжинирингу и бинарному анализу. Проверьте свои навыки в области информационной безопасности.",
    status: "FINISHED",
    topics: ["ML", "Python", "React", "Go"],
    total_participants: 847,
    total_teams: 142,
    min_team_size: 1,
    max_team_size: 4,
    max_participants: 1000,
    event_location: "Moscow",
    start_date: "2026-03-18T18:00:00",
    end_date: "2026-03-20T18:00:00",
    prizes: [
      { id: 1, title: "1-е место", reward: "250000" },
      { id: 2, title: "2-е место", reward: "100000" },
      { id: 3, title: "3-е место", reward: "50000" },
    ],
    submission_requirements: [
      "Команда от 1 до 4 человек",
      "Регистрация на платформе CTF",
      "Решенные задачи (флаги)",
      "Write-up для топ-3 решений",
    ],
  },
  {
    id: 1,
    title: "HackPrimeCode Лето 2026",
    description:
      "Флагманский хакатон от платформы. 48 часов интенсивной командной работы над реальными задачами от наших партнёров. Создавайте инновационные решения, получайте ценный опыт и выигрывайте крупные денежные призы.",
    status: "FINISHED",
    topics: ["ML", "Python", "React", "Go"],
    total_participants: 847,
    total_teams: 142,
    min_team_size: 1,
    max_team_size: 4,
    max_participants: 1000,
    event_location: "Moscow",
    start_date: "2026-06-25T18:00:00",
    end_date: "2026-06-29T18:00:00",
    prizes: [
      { id: 1, title: "1-е место", reward: "300000" },
      { id: 2, title: "2-е место", reward: "150000" },
      { id: 3, title: "3-е место", reward: "50000" },
    ],
    submission_requirements: [
      "Команда от 1 до 4 человек",
      "Регистрация обязательна до начала хакатона",
      "Наличие GitHub аккаунта",
      "Готовность работать 48 часов",
    ],
  },
];
